[Task 7] Create chat for two applications. Create a chat
JuliaKholodetska/Task5-6-7-Full-Stack-JS-Internship pull request #13
Opened 2021-04-21 12:37 UTC by JuliaKholodetska

2021-04-22 09:40 UTC, MariiaKolisnyk requested changes

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/routes/index.js
> +routes.use("/api/message", messageRouter);
it should be `messages`

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/routes/messageRouter.js
> +	"/all",
according to REST you do not need `all`
- GET /messages                    - get all the messages
- GET /messages/:id              - get a message by id 

or
- GET /messages/:roomId  - get all the messages in the room

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/controllers/messageController.js
> +			where: { roomId: req.query.room },
`room` rename to `roomId` and it should be passed through the `param` but not `query`.

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/routes/messageRouter.js
> +	"/all",
btw, you called the route `all` however it returns not all messages but only for specific room

2021-04-22 09:40 UTC, MariiaKolisnyk commented on client/src/components/InfoBar.js
> +		<div className="text-infobar">Chat with Admin</div>
infoBar -> info-bar

2021-04-22 09:40 UTC, MariiaKolisnyk commented on client/src/index.css
> +button.primary.join {
empty lines?

2021-04-22 09:40 UTC, MariiaKolisnyk commented on client/src/index.css
> +.messageText {
all the classes names should be with dash

2021-04-22 09:40 UTC, MariiaKolisnyk commented on client/src/pages/ChatPage.js
> +		});
I think we need to move this kind of logic to a service or something like this. we usually do mot mix components and api calls
I'm not sure what is the best way to do it in React, could you please investigate this?

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/controllers/messageController.js
> +			where: { roomId: req.query.room },
what about validation?

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/services/chatService.js
> +export let chatService = {
why is it `let`?

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/services/chatService.js
> +let userSocketIdHashMap = {};
why is it let?

2021-04-22 09:40 UTC, MariiaKolisnyk commented on backend/services/chatService.js
> +export let chatService = {
please make a class `chatService`

2021-04-23 07:32 UTC, MariiaKolisnyk requested changes

2021-04-23 07:32 UTC, MariiaKolisnyk commented on backend/controllers/messageController.js
> +			String(req.user.id) !== String(req.params.roomId)
- please, extract all needed values from `req` to constants.
- `req.user.isAdmin === false` -> `!req.user.isAdmin`
- I don't think we need `String`

2021-04-23 08:38 UTC, JuliaKholodetska commented on backend/controllers/messageController.js
> +			String(req.user.id) !== String(req.params.roomId)
там string потрібен бо в req.user.id це число а в req.params.roomId це строка

2021-04-23 08:38 UTC, JuliaKholodetska commented on client/src/services/chatService.js
> +	sendMessage(message) {
not optionally asyn, there is a return promise

2021-04-23 08:38 UTC, JuliaKholodetska commented on client/src/services/chatService.js
> +	_sendJoinChat() {
ok

2021-04-27 05:24 UTC, MariiaKolisnyk approved these changes

2021-04-27 05:24 UTC, MariiaKolisnyk commented on backend/server.js
>  import PaymentStatus from "./models/paymenrStatusModel.js";
please fix the typo in the file name -  `models/paymenrStatusModel.js`

2021-04-27 05:24 UTC, MariiaKolisnyk commented on client/src/services/chatService.js
> +	sendMessage(message) {
I do not get it - if we are returning Promise this is async, what am I missing?

2021-04-27 05:24 UTC, MariiaKolisnyk commented on client/src/services/chatService.js
> +	_sendJoinChat() {
could you please remove `-`?

2021-04-27 06:19 UTC, merged